### ISSUE TITLE
项目拉到本地后，运行demo 使用LicensePlate会闪退到上一界面

### ISSUE THREAD

**Issue by ccjksxll** [shouzhong/Scanner#21]
08-21 16:50:39.833 23091-23091/? I/art: Late-enabling -Xcheck:jni
08-21 16:50:39.867 23091-23091/? D/TidaProvider: TidaProvider()
08-21 16:50:39.878 23091-23091/? W/ReflectionUtils: java.lang.NoSuchMethodException: android.os.MessageQueue#enableMonitor()#bestmatch
        at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:338)
        at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:375)
        at miui.util.ReflectionUtils.callMethod(ReflectionUtils.java:800)
        at miui.util.ReflectionUtils.tryCallMethod(ReflectionUtils.java:818)
        at android.os.BaseLooper.enableMonitor(BaseLooper.java:47)
        at android.os.Looper.prepareMainLooper(Looper.java:111)
        at android.app.ActivityThread.main(ActivityThread.java:5584)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
08-21 16:50:39.916 23091-23091/com.shouzhong.scanner.demo W/ResourceType: No package identifier when getting name for resource number 0x00000000
08-21 16:50:40.002 23091-23091/com.shouzhong.scanner.demo W/ResourceType: No package identifier when getting name for resource number 0x00000000
08-21 16:50:40.014 23091-23091/com.shouzhong.scanner.demo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-21 16:50:40.031 23091-23119/com.shouzhong.scanner.demo W/ResourceType: No package identifier when getting name for resource number 0x00000000
08-21 16:50:40.055 23091-23091/com.shouzhong.scanner.demo D/AccessibilityManager: current package=com.shouzhong.scanner.demo, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=false, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
08-21 16:50:40.069 23091-23091/com.shouzhong.scanner.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
08-21 16:50:40.070 23091-23091/com.shouzhong.scanner.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
08-21 16:50:40.124 23091-23119/com.shouzhong.scanner.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --non-interactive --runtime-arg -Xms64m --runtime-arg -Xmx512m -j4 --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/system/app/MiuiContentCatcher/MiuiContentCatcher.apk --oat-file=/data/dalvik-cache/arm/system@app@MiuiContentCatcher@MiuiContentCatcher.apk@classes.dex) because non-0 exit status
08-21 16:50:40.146 23091-23119/com.shouzhong.scanner.demo W/System: ClassLoader referenced unknown path: /system/app/MiuiContentCatcher/lib/arm64
08-21 16:50:40.149 23091-23130/com.shouzhong.scanner.demo D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-21 16:50:40.166 23091-23119/com.shouzhong.scanner.demo D/ViewContentFactory: initViewContentFetcherClass
08-21 16:50:40.166 23091-23119/com.shouzhong.scanner.demo D/ViewContentFactory: getInterceptorPackageInfo
08-21 16:50:40.168 23091-23119/com.shouzhong.scanner.demo D/ViewContentFactory: getInitialApplication took 2ms
08-21 16:50:40.169 23091-23119/com.shouzhong.scanner.demo D/ViewContentFactory: packageInfo.packageName: com.miui.catcherpatch
08-21 16:50:40.170 23091-23119/com.shouzhong.scanner.demo W/ResourceType: No package identifier when getting name for resource number 0x00000000
08-21 16:50:40.233 23091-23130/com.shouzhong.scanner.demo I/Adreno: QUALCOMM build                   : 018a571, I7cc9bddfce
    Build Date                       : 06/05/17
    OpenGL ES Shader Compiler Version: XE031.08.00.00
    Local Branch                     : 
    Remote Branch                    : quic/LA.UM.5.3_rb1.1
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
08-21 16:50:40.246 23091-23130/com.shouzhong.scanner.demo I/OpenGLRenderer: Initialized EGL, version 1.4
08-21 16:50:40.247 23091-23119/com.shouzhong.scanner.demo W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --non-interactive --runtime-arg -Xms64m --runtime-arg -Xmx512m -j4 --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/system/app/CatcherPatch/CatcherPatch.apk --oat-file=/data/dalvik-cache/arm/system@app@CatcherPatch@CatcherPatch.apk@classes.dex) because non-0 exit status
08-21 16:50:40.259 23091-23119/com.shouzhong.scanner.demo W/System: ClassLoader referenced unknown path: /system/app/CatcherPatch/lib/arm64
08-21 16:50:40.264 23091-23119/com.shouzhong.scanner.demo D/ViewContentFactory: initViewContentFetcherClass took 98ms
08-21 16:50:40.265 23091-23119/com.shouzhong.scanner.demo I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
08-21 16:50:40.265 23091-23119/com.shouzhong.scanner.demo D/ViewContentFactory: createInterceptor took 99ms
08-21 16:50:40.271 23091-23119/com.shouzhong.scanner.demo I/ContentCatcher: Interceptor : Catcher list invalid for com.shouzhong.scanner.demo@com.shouzhong.scanner.demo.MainActivity@59871598
08-21 16:50:40.273 23091-23119/com.shouzhong.scanner.demo I/ContentCatcher: Interceptor : Get featureInfo from config pick_mode
08-21 16:56:32.472 23091-23091/com.shouzhong.scanner.demo I/Timeline: Timeline: Activity_launch_request time:776163204
08-21 16:56:32.510 23091-23119/com.shouzhong.scanner.demo D/ViewContentFactory: initViewContentFetcherClass
08-21 16:56:32.510 23091-23119/com.shouzhong.scanner.demo I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
08-21 16:56:32.510 23091-23119/com.shouzhong.scanner.demo D/ViewContentFactory: createInterceptor took 1ms
08-21 16:56:32.511 23091-23119/com.shouzhong.scanner.demo I/ContentCatcher: Interceptor : Catcher list invalid for com.shouzhong.scanner.demo@com.shouzhong.scanner.demo.ScannerActivity@91831977
08-21 16:56:32.511 23091-23119/com.shouzhong.scanner.demo I/ContentCatcher: Interceptor : Get featureInfo from config pick_mode
08-21 16:56:32.521 23091-23091/com.shouzhong.scanner.demo V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@fd0bf63
08-21 16:56:32.522 23091-23091/com.shouzhong.scanner.demo V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@fc3d760
08-21 16:56:32.711 23091-23130/com.shouzhong.scanner.demo D/OpenGLRenderer: endAllStagingAnimators on 0xab33c5e0 (RippleDrawable) with handle 0xab28d120

**Comment by shouzhong** [comment]
有加群吗，这里交流不方便
