### ISSUE TITLE
图片文字识别怎么不能使用,一点就崩溃,缺少.so文件

### ISSUE THREAD

**Issue by 900326** [shouzhong/Scanner#61]

**Comment by shouzhong** [comment]
你是用依赖还是直接编这个项目，如果直接编译的，是会确实

**Comment by shouzhong** [comment]
你可以从依赖里面把so包复制出来

**Comment by 900326** [comment]
报错日志是这样的 ,从依赖里面把so包复制出来---------这个是从哪里复制到哪里,除了复制外,还需要修改什么地方吗
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shouzhong.scanner.demo-NpGd_F9PNabwwj4FMSXjjQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.shouzhong.scanner.demo-NpGd_F9PNabwwj4FMSXjjQ==/lib/arm, /data/app/com.shouzhong.scanner.demo-NpGd_F9PNabwwj4FMSXjjQ==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib, /system/product/lib]]] couldn't find "libTextRecognition.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.shouzhong.text.TextRecognition.<clinit>(TextRecognition.java:6)
        at com.shouzhong.text.TextRecognition.recognize(Native Method)
        at com.shouzhong.scanner.ScannerUtils.decodeText(ScannerUtils.java:263)
        at com.shouzhong.scanner.demo.MainActivity$1.run(MainActivity.java:45)
        at java.lang.Thread.run(Thread.java:929)

**Comment by 900326** [comment]
libTextRecognition.so,没找到有这样名字的.so

**Comment by shouzhong** [comment]
你自己本地加我依赖写个demo，然后打个apk，用压缩软件打开apk就能找到
